# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  manifest:
    cmds:
      - timoni build dot-kubernetes timoni | tee package/all.yaml
  test:
    cmds:
      - kind create cluster
      - helm repo update
      - timoni build dot-kubernetes timoni | tee package/all.yaml && kubectl kuttl test --timeout 600
      - kind delete cluster
  timon:
    dir: timoni
    cmds:
      - timoni build dot-kubernetes .
  publish:
#    requires up login command
#    dir: timoni
    cmds:

      - up xpkg build --name k8s.xpkg
#      - up xpkg push \
#        --package k8s.xpkg \
#        xpkg.upbound.io/$UP_ACCOUNT/dot-kubernetes:$VERSION
  start:
    cmds:
      - kind create cluster
      - helm repo add crossplane-stable https://charts.crossplane.io/stable && helm repo update
      - helm install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane
      - helm repo add komodorio https://helm-charts.komodor.io
      - helm upgrade --install komoplane komodorio/komoplane -n crossplane-ui --create-namespace
      - kubectl -n crossplane-system wait deployment crossplane --for=condition=Available --timeout=180s
      - kubectl get pods -n crossplane-system
      - kubectl get deployments -n crossplane-system
#      - task: argocd:install
#                - task: crossplane:setup
        #      - task: kubevela:install
#                - helm install kube-prometheus bitnami/kube-prometheus -n prometheus --create-namespace --set installCRDs=true
#                - helm upgrade --install k8s-watcher komodorio/k8s-watcher --set apiKey=4b11ca71-2163-45d8-88a8-bd0c0d450657 --set watcher.clusterName=master-cluster  --wait --timeout=90s && open https://app.komodor.com/main/services
