name: build
on:
  push:
    branches:
      - main
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Generate manifests
        run: |
          timoni build dot-kubernetes timoni >package/all.yaml
          head -n -1 package/all.yaml > package/all.yaml.tmp
          mv package/all.yaml.tmp package/all.yaml
          cat package/all.yaml
      - name: Run tests
        run: |
          (
            set -x; cd "$(mktemp -d)" &&
            OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
            ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
            KREW="krew-${OS}_${ARCH}" &&
            curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
            tar zxvf "${KREW}.tar.gz" &&
            ./"${KREW}" install krew
          )
          export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
          kubectl krew install kuttl
          helm repo add crossplane-stable https://charts.crossplane.io/stable
          kubectl kuttl test --start-kind --skip-delete --skip-cluster-delete --timeout 120 tests/
      - name: Build the package
        run: |
          cd package
          curl -sL https://cli.upbound.io | sh
          ./up login --token ${{ secrets.UP_TOKEN }}
          ./up xpkg build --name kubernetes.xpkg
          ./up xpkg push --package kubernetes.xpkg xpkg.upbound.io/${{ secrets.UP_ACCOUNT }}/dot-kubernetes:v0.11.${{ github.run_number }}
      - name: Update config
        run: |
          yq --inplace ".spec.package = \"xpkg.upbound.io/devops-toolkit/dot-kubernetes:v0.11.${{ github.run_number }}\"" config.yaml
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Config update [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CROSSPLANE_TOKEN }}
          branch: ${{ github.ref }}
